# Generated by Django 5.2.5 on 2025-08-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lmsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="total_rental",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=3, null=True
            ),
        ),
    ]
